- id: ansible-lint-conda
  name: ansible-lint-conda
  description: 'This hook runs ansible-lint.'
  entry: ansible-lint -v --force-color
  language: conda
  # do not pass files to ansible-lint, see:
  # https://github.com/ansible/ansible-lint/issues/611
  pass_filenames: false
  always_run: true
